### ISSUE TITLE
TypeError: Yp.includes is not a function

### ISSUE THREAD

**Issue by jaggedsoft** [ebemunk/node-uci#6]
I'm getting this error on some games, and I can't seem to figure it out. It works most of the time. Any ideas?
```
TypeError: Yp.includes is not a function
    at node_modules/node-uci/lib/index.js:1:11821
    at node_modules/node-uci/lib/index.js:1:10014
    at ae (node_modules/node-uci/lib/index.js:1:11109)
    at node_modules/node-uci/lib/index.js:1:11195
    at le (node_modules/node-uci/lib/index.js:1:11399)
    at pe (node_modules/node-uci/lib/index.js:1:11696)
    at Ht (node_modules/node-uci/lib/index.js:1:9603)
    at Array.reduce (native)
    at t.<anonymous> (node_modules/node-uci/lib/index.js:5:10856)
    at r (node_modules/node-uci/lib/index.js:1:17238)
    at a._invoke (node_modules/node-uci/lib/index.js:1:18658)
    at a.t.(anonymous function) [as next] (node_modules/node-uci/lib/index.js:1:17417)
    at r (node_modules/node-uci/lib/index.js:2:1735)
    at node_modules/node-uci/lib/index.js:2:1837
    at a (node_modules/node-uci/lib/index.js:1:31025)
    at node_modules/node-uci/lib/index.js:1:31149
```

My code:

```
const Engine = require('node-uci').Engine
const engine = new Engine('/usr/games/brainfish/stockfish')
engine.chain()
.init()
.setoption('Hash',memory)
.setoption('Threads',threads)
.setoption('Ponder','false')
.setoption('SyzygyPath','/usr/games/tablebase')
.setoption('BookPath','/usr/games/brainfish/Cerebellum_Light.bin')
.setoption('Book Move2 Probability',move2)
.position('startpos',movelist)
//.go({depth: 15})
//.go({movetime: 16000})
//.go({nodes: 2500000})
.go(speed)
.then(result => {
    console.log(result.bestmove);
    process.exit();
}).catch(err => {
    if (err.stack) {
      console.log('\nStacktrace:')
      console.log('====================')
      console.log(err.stack);
    }
    console.error("bestmove.js error:",err);
    process.exit();
});
```

**Comment by ebemunk** [comment]
I can't tell, Yp refers to the minified `INFO_NUMBER_TYPES` constant in parseUtil.js.

One idea is that maybe you're not including `babel-runtime` in your own project, but that seems unlikely if the other async functions work.

If you run a failing case with `DEBUG=uci:Engine:log` it might bring clarity to the issue. That will print out all communication between node-uci and the engine.

i.e. `DEBUG=uci:Engine:log myscript.js > engineLog.txt` and paste it here, we can see if maybe the engine is sending weird stuff.

**Comment by jaggedsoft** [comment]
Not much info here, it does everything, completes successfully, gets the best move, and then has an error afterwards and since I can't suppress it the program terminates. Thanks for your help!
```
 +639ms
  uci:Engine:log from engine: info depth 16 seldepth 26 multipv 1 score cp 258 nodes 2515605 nps 875907 hashfull 8 tbhits 0 time 2872 pv f3g5 c6e7 d3d4 e5d4 c3d4 d6d5 d4c5 d5c4 b1a3 e7c6 d1d8 f8d8 g3c7 d8d4 a3b5 d4e4 g5e4 f6e4 b5d6 e4c5 d6c4
bestmove f3g5 ponder c6e7

 +111ms
bestmove.js error: [TypeError: Yp.includes is not a function]
```

**Comment by jaggedsoft** [comment]
I believe this was the output from stockfish that caused the problem:
```Could not mmap() /usr/games/tablebase/KQPPvKQ.rtbz```

Solved by downloading the missing files from http://tablebase.sesse.net/syzygy/6-DTZ/

**Comment by ebemunk** [comment]
Makes sense, if this doesn't generally result in engine error then maybe its best to ignore unparseable lines. Will think about it, but need to investigate first.
